# Generated by Django 6.0.2 on 2026-02-20 06:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique receipt identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number (1, 2, 3...)')),
                ('student_name', models.CharField(db_index=True, max_length=200)),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('kit_books_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activity_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('uniform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source', models.CharField(choices=[('upload', 'Excel Upload'), ('manual_edit', 'Manual Edit'), ('api', 'API')], default='upload', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_versions', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='receipts.receipt')),
            ],
            options={
                'db_table': 'receipt_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_receipts', to='receipts.receiptversion'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='receipts.receipt')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='receipts.receiptversion')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('max_access', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='receipts.receipt')),
            ],
            options={
                'db_table': 'share_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('records_inserted', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='receiptversion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='receipts.uploadbatch'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='receipts_receipt_0f1a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'created_at'], name='receipts_status_3c94c2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['receipt', 'changed_at'], name='audit_logs_receipt_4492e7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['field_name'], name='audit_logs_field_n_39dc46_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['changed_at'], name='audit_logs_changed_35eb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['token'], name='share_links_token_5e7a57_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['expires_at'], name='share_links_expires_c51b58_idx'),
        ),
        migrations.AddIndex(
            model_name='sharelink',
            index=models.Index(fields=['is_active'], name='share_links_is_acti_ab2055_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['uploaded_at'], name='upload_batc_uploade_0131f7_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['status'], name='upload_batc_status_6082ee_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['receipt', 'version_number'], name='receipt_ver_receipt_1b6acb_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['student_name'], name='receipt_ver_student_27e781_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['class_name'], name='receipt_ver_class_n_47fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['date'], name='receipt_ver_date_19923d_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['payment_mode'], name='receipt_ver_payment_862b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptversion',
            index=models.Index(fields=['changed_at'], name='receipt_ver_changed_7001d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receiptversion',
            unique_together={('receipt', 'version_number')},
        ),
    ]
